version: '3.8'

services:
  web:
    build: .
    ports:
      - "8000:5000"
    volumes:
      - .:/app
    environment:
      - FLASK_APP=app
      - FLASK_ENV=development
      - MONGODB_URI=mongodb://mongodb:27017/finance_tracker
    depends_on:
      - mongodb
    networks:
      - app-network

  mongodb:
    image: mongo:latest
    container_name: finance-tracker-mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "mongo", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5

networks:
  app-network:
    driver: bridge

volumes:
  mongodb_data:
