name: deploy to digital ocean droplet

on:
  workflow_dispatch:

  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: SSH into Droplet and Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DIGITALOCEAN_IP }}
          username: ${{ secrets.DIGITALOCEAN_USER }}
          key: ${{ secrets.DIGITALOCEAN_KEY }}
          script: |
            cd /root/5-final-fizzbuzz
            git pull
            docker pull ${{ secrets.DOCKERHUB_USERNAME }}/finance-tracker-backend:latest
            docker pull ${{ secrets.DOCKERHUB_USERNAME }}/finance-tracker-frontend:latest
            
            docker-compose down
            docker-compose up -d
